"""Generate a deterministic firmware source identity before PlatformIO builds."""

from hashlib import sha256
from pathlib import Path
import subprocess


ROOT = Path(__file__).resolve().parent.parent if "__file__" in globals() else Path.cwd()
OUTPUT = ROOT / "include" / "generated" / "build_identity.h"


def generate() -> None:
    try:
        commit = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True
        ).strip()
        commit_bytes = bytes.fromhex(commit)
    except (OSError, subprocess.CalledProcessError, ValueError):
        commit_bytes = bytes(20)

    digest = sha256()
    inputs = sorted((ROOT / "src").rglob("*.c"))
    inputs += sorted(p for p in (ROOT / "include").rglob("*.h") if p != OUTPUT)
    inputs += [ROOT / "platformio.ini", ROOT / "tools" / "build_identity.py"]
    for path in inputs:
        digest.update(path.relative_to(ROOT).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")

    def initializer(value: bytes) -> str:
        return ", ".join(f"0x{byte:02x}" for byte in value)

    content = (
        "/* Generated by tools/build_identity.py; do not edit. */\n"
        "#pragma once\n"
        "#include <stdint.h>\n"
        f"static const uint8_t build_commit_bytes[20] = {{{initializer(commit_bytes)}}};\n"
        f"static const uint8_t build_source_bytes[32] = {{{initializer(digest.digest())}}};\n"
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
        OUTPUT.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    generate()
else:
    Import("env")  # type: ignore[name-defined]  # provided by SCons
    ROOT = Path(env["PROJECT_DIR"])
    OUTPUT = ROOT / "include" / "generated" / "build_identity.h"
    generate()
